import type { Metadata } from "next";
import { Header, Footer } from "@/components/ui";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Leb1ga Twitch Giveaway",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
